### Crear un nuevo PQR (Petición)
POST http://localhost:8000/pqr/
Content-Type: application/json

{
  "id_solicitud": 1,
  "id_usuario": 1,
  "id_profesional": 1,
  "tipo": "peticion",
  "descripcion": "¿Mañana puede venir?",
  "estado": "pendiente"
}

### Separador para las solicitudes ###
### Crear un PQR (Queja)
POST http://localhost:8000/pqr/
Content-Type: application/json

{
  "id_solicitud": 14,
  "id_usuario": 2,
  "id_profesional": 2,
  "tipo": "queja",
  "descripcion": "El profesional llegó 1 hora tarde.",
  "estado": "pendiente"
}

### Separador para las solicitudes ###
### Crear un PQR (Sugerencia)
POST http://localhost:8000/pqr/
Content-Type: application/json

{
  "id_solicitud": 15,
  "id_usuario": 3,
  "id_profesional": 3,
  "tipo": "sugerencia",
  "descripcion": "Sería útil poder pagar en línea.",
  "estado": "resuelto"
}

### Separador para las solicitudes ###
### Obtener todos los PQRs
GET http://localhost:8000/pqr/


### Separador para las solicitudes ###
### Obtener un PQR específico por ID
GET http://localhost:8000/pqr/16


### Separador para las solicitudes ###
### Actualizar un PQR existente
PUT http://localhost:8000/pqr/16
Content-Type: application/json

{
  "id_solicitud": 13,
  "id_usuario": 1,
  "id_profesional": 1,
  "tipo": "peticion",
  "descripcion": "¿Podría adelantar la visita a la mañana? - ACTUALIZADA",
  "estado": "en_proceso"
}


### Separador para las solicitudes ###
### Eliminar un PQR
DELETE http://localhost:8000/pqr/16